version: '3.8'  # The version of Docker Compose syntax used

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-API               # The Dockerfile to use for building the `api` service
    ports:
      - "48019:8080"                          # Maps port 80 inside the container to port 8080 on the host machine
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Sets environment variable for ASP.NET Core (Development mode)
      - ConnectionStrings__ApplicationContext=Server=db;Database=YourDatabase;User Id=sa;Password=TestPas$123!@#; # Update with your DB connection
    depends_on:
      - db                                 # Ensures that the `db` service starts before the `api` service
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"  # Microsoft SQL Server image
    environment:
      SA_PASSWORD: "TestPas$123!@#"         # Set the SA password
      ACCEPT_EULA: "Y"                    # Required to accept the SQL Server EULA
    ports:
      - "1433:1433"                       # Expose SQL Server on port 1433
    volumes:
      - sql_data:/var/opt/mssql            # Persist database data across container restarts
volumes:
  sql_data:                               # Volume to persist the database data
