version: '3.8'

services:
  api:
    build:
      context: ./OracleCMS.CarStocks.API
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "testpassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
